name: Node.js test CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      NODE_ENV_TEST: local
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i

      - run: npm test

