name: Node.js test CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: pnpm ci

      - run: pnpm test

